version: '3.4'

services:
  authenticationauthorization.api:
    image: ${DOCKER_REGISTRY-}authenticationauthorizationapi
    build:
      context: .
      dockerfile: Services/AuthenticationAuthorization/AuthenticationAuthorization.API/Dockerfile

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile


  rating.api:
    image: ${DOCKER_REGISTRY-}ratingapi
    build:
      context: .
      dockerfile: Services/Rating/Rating.API/Dockerfile


  reservations.api:
    image: ${DOCKER_REGISTRY-}reservationsapi
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.API/Dockerfile


  roommanaging.api:
    image: ${DOCKER_REGISTRY-}roommanagingapi
    build:
      context: .
      dockerfile: Services/ManagingRooms/RoomManaging.API/Dockerfile

