version: '3.4'

services:
  reservationsdb:
    image: mongo

  checkinoutdb:
    image: postgres

  roommanagingdb:
    image: redis:alpine

  pghoteladmin:
    image: dpage/pgadmin4

  mssql_identity:
    image: mcr.microsoft.com/mssql/server:2022-latest

  ratingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile

  rating.api:
    image: ${DOCKER_REGISTRY-}ratingapi
    build:
      context: .
      dockerfile: Services/Rating/Rating.API/Dockerfile

  reservations.api:
    image: ${DOCKER_REGISTRY-}reservationsapi
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.API/Dockerfile

  roommanaging.api:
    image: ${DOCKER_REGISTRY-}roommanagingapi
    build:
      context: .
      dockerfile: Services/ManagingRooms/RoomManaging.API/Dockerfile

  checkinoutapi:
    image: checkinoutapi
    build:
      context: .
      dockerfile: Services/CheckInOut/CheckInOut.API/Dockerfile

  roommanaging.grpc:
    image: ${DOCKER_REGISTRY-}roommanaginggrpc
    build:
      context: .
      dockerfile: Services/ManagingRooms/RoomManaging.GRPC/Dockerfile

  reservations.grpc:
    image: ${DOCKER_REGISTRY-}reservationsgrpc
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.GRPC/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data:
  ratingdb_data:
  mssql_data_identity:




