version: '3.4'

services:
  reservationsdb:
    container_name: reservationsdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  checkinoutdb:
    container_name: checkinoutdb
    restart: always
    environment:
      - POSTGRES_USER=isidora
      - POSTGRES_PASSWORD=271020
      - POSTGRES_DB=CheckInOutDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  roommanagingdb:
    container_name: roommanagingdb
    restart: always
    ports:
        - "6379:6379"

  pghoteladmin:
    container_name: pghoteladmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=isidoraburmaz@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=271020
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  mssql_identity:
    container_name: mssql_identity
    user: root
    environment:
      - MSSQL_SA_PASSWORD=rs2_IdentityMicroservice
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data_identity:/var/opt/mssql/data
        
  ratingdb:
    container_name: ratingdb
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
    restart: always
    ports:
      - "1439:1433"
    volumes:
      - ratingdb_data:/var/opt/mssql/data
        
  identitydb:
    container_name: identitydb
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
    restart: always
    ports:
      - "1440:1433"
    volumes:
      - identitydb_data:/var/opt/mssql/data

  payment.api:
    container_name: paymentapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8001:8080"

  rating.api:
    container_name: ratingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:RatingConnectionString=Server=ratingdb;Database=RatingDb;User Id=sa;Password=Passw0rd;TrustServerCertificate=True;Encrypt=False;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
      - ratingdb
    ports:
      - "8002:8080"

  reservations.api:
    container_name: reservationsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionSettings=mongodb://reservationsdb:27017" 
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - reservationsdb
      - rabbitmq
    ports:
      - "8003:8080"

  roommanaging.api:
    container_name: roommanagingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=roommanagingdb:6379"
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - roommanagingdb
    ports:
      - "8004:8080"

  roommanaging.grpc:
    container_name: roommanaginggrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=roommanagingdb:6379"
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - roommanagingdb
    ports:
      - "8006:8080"

  reservations.grpc:
    container_name: reservationsgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionSettings=mongodb://reservationsdb:27017" 
    depends_on:
      - reservationsdb
    ports:
      - "8007:8080"
        
  checkinoutapi:
    container_name: checkinoutapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=Server=checkinoutdb;Port=5432;Database=CheckInOutDb;User Id=isidora;Password=271020;"
      - "GrpcSettings:UserReservationsUrl=http://reservations.grpc:8080"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
      - checkinoutdb
      - reservations.grpc
    ports:
      - "8005:8080"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:IdentityConnectionString=Server=identitydb;Database=IdentityDb;User Id=sa;Password=Passw0rd;TrustServerCertificate=True;Encrypt=False;"
    depends_on:
      - identitydb
    ports:
      - "8000:8080"
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
